### PR TITLE
Don't set Bcc header as some mail servers forward it to the recipient.

### PR DESCRIPTION
**Pull request by thomasst**
It is enough to specify the BCC addresses in RCPT TO.

### CODE REVIEW

**Comment by noirbizarre** [comment]
Is it possible to have a little background on this ?

Not being able to BCC can be a lack in some situations.
Isn't it possible to make it configurable ?

**Comment by davidism** [comment]
It still [sends to all recipients in the `recipients`, `bcc`, and `cc` lists][1], it just doesn't set the `Bcc` header, since some servers apparently forward the header rather than stripping it, defeating the "blind" part of bcc.

[1]: https://github.com/closeio/flask-mail/blob/36c63c8a9edc4a02925bd5fee4d1cdf6b0f130f1/flask_mail.py#L278-L280

**Comment by noirbizarre** [comment]
OK, if I summarize, BCC recipients will still receive the mail, TO and CC recipients won't see BCC recipients. It's only the header that is skipped ?

**Comment by davidism** [comment]
Yes.  You could easily verify this by sending an email with all three and observing the behavior.

**Comment by noirbizarre** [comment]
Thanks

**Pull request merged**
